=== mikestowe/raml08vsraml10/schemas/json/books.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "isbn": {
      "type": "string"
    },
    "bookTitle": {
      "type": "string"
    },
    "synopsis": {
      "type": "string"
    },
    "author": {
      "type": "object",
      "properties": {
        "authorId": {
          "type": "integer"
        },
        "firstName": {
          "type": "string"
        },
        "lastName": {
          "type": "string"
        },
        "_links": {
          "type": "object",
          "properties": {
            "self": {
              "type": "object",
              "properties": {
                "title": {
                  "type": "string"
                },
                "href": {
                  "type": "string"
                },
                "methods": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                }
              },
              "required": [
                "title",
                "href",
                "methods"
              ]
            },
            "books": {
              "type": "object",
              "properties": {
                "title": {
                  "type": "string"
                },
                "href": {
                  "type": "string"
                },
                "methods": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                }
              },
              "required": [
                "title",
                "href",
                "methods"
              ]
            }
          },
          "required": [
            "self",
            "books"
          ]
        }
      },
      "required": [
        "authorId",
        "firstName",
        "lastName",
        "_links"
      ]
    }
  },
  "required": [
    "isbn",
    "bookTitle",
    "synopsis",
    "author"
  ]
}

=== mikestowe/raml08vsraml10/examples/json/books.json
{
  "isbn" : "",
  "bookTitle" : "Undisturbed REST: a Guide to Designing the Perfect API",
  "synopsis" : "Learn the basics of REST and design best practices with modern technologies",
  "author" : {
    "authorId" : 5,
    "firstName" : "Michael",
    "lastName" : "Stowe",
    
    "_links" : {
      "self" : {
        "title" : "View Mike's Information",
        "href" : "/authors/5",
        "methods" : ["get"]
      },
      
      "books" : {
        "title" : "Get a List of Mike's Books",
        "href" : "/books?authorId=5",
        "methods" : ["get"]
      }
    
    }
  }
}
